import MUIProvider from "@/themes/mui.provider";
import ReactQueryProvider from "@/services/queries/react-query/rq.provider";
import ReduxProvider from "@/store/provider";
import Layout from "@/layouts";
import "../styles/index.css";
import fontsVariables from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "initial-scale=1, width=device-width",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //? for rtl languages
    // <html lang="fa" dir="rtl">
    <html lang="en">
      <body className={fontsVariables}>
        <ReactQueryProvider>
          <ReduxProvider>
            <MUIProvider>
              <Layout>{children}</Layout>
            </MUIProvider>
          </ReduxProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
